[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "azure.storage.blob"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Type/Connector", "Area/Storage & File Management", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.storage.blob"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "azure.storage.blob-native"
version = "@toml.version@"
path = "../native/build/libs/azure.storage.blob-native-@project.version@.jar"
